// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZvIAalqLSitObf6IGbXywSX0jcAYUFqk',
    appId: '1:568573984383:web:f52f54128359bc1edb894a',
    messagingSenderId: '568573984383',
    projectId: 'luxevista-16304',
    authDomain: 'luxevista-16304.firebaseapp.com',
    storageBucket: 'luxevista-16304.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4dg6gaRJUgfpHiwPqtG1n62IdIrApkg',
    appId: '1:568573984383:android:72853a7d6f6a7e09db894a',
    messagingSenderId: '568573984383',
    projectId: 'luxevista-16304',
    storageBucket: 'luxevista-16304.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVVDFIViqxJYmdobCiDuMoAogGSecRKg',
    appId: '1:568573984383:ios:1861f3c7c554dfb8db894a',
    messagingSenderId: '568573984383',
    projectId: 'luxevista-16304',
    storageBucket: 'luxevista-16304.firebasestorage.app',
    iosBundleId: 'com.example.luxevistaResort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXVVDFIViqxJYmdobCiDuMoAogGSecRKg',
    appId: '1:568573984383:ios:1861f3c7c554dfb8db894a',
    messagingSenderId: '568573984383',
    projectId: 'luxevista-16304',
    storageBucket: 'luxevista-16304.firebasestorage.app',
    iosBundleId: 'com.example.luxevistaResort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZvIAalqLSitObf6IGbXywSX0jcAYUFqk',
    appId: '1:568573984383:web:5cb2ac84842df3ffdb894a',
    messagingSenderId: '568573984383',
    projectId: 'luxevista-16304',
    authDomain: 'luxevista-16304.firebaseapp.com',
    storageBucket: 'luxevista-16304.firebasestorage.app',
  );
}
